### ISSUE TITLE
[FEAT] 공통 컴포넌트 기능 추가 요청

### ISSUE THREAD

**Issue by ding-co** [depromeet/ggogeet-client#32]
## ✨ 기능 설명

- Input 컴포넌트에 X 버튼 기능 추가

## ✨ 개발 목록

- [  ] Input 컴포넌트 X 버튼 기능

## ✨ 스크린샷

<img width="289" alt="Screenshot 2022-11-30 at 8 53 40 PM" src="https://user-images.githubusercontent.com/80014673/204789635-fdd250cc-c158-4e6a-acb2-9daf4aba26aa.png">

**Comment by numeru** [comment]
이건 동규님께서 봐주셔야 할 것 같네요!

@Dongkyuuuu

**Comment by Dongkyuuuu** [comment]
@numeru @ding-co 
한가지 의견을 구하고 싶은게 X 버튼을 받을 수 있게 별도로 구현을 따로 해야할까요? 아니면 type='search'에서 제공하는 아이콘을 수정하는 방향으로 가는게 좋을까요?

**Comment by ding-co** [comment]
> @numeru @ding-co 한가지 의견을 구하고 싶은게 X 버튼을 받을 수 있게 별도로 구현을 따로 해야할까요? 아니면 type='search'에서 제공하는 아이콘을 수정하는 방향으로 가는게 좋을까요?

개인적으로 X 버튼 받도록 하는 것이 나을 것 같습니다.
현재 스크린샷의 input은 search type이라기 보다는 text에 좀 더 가까울 것 같습니다.
(물론 현재 친구 목록 검색 시 뜨도록 하는 기능이 있긴 하지만 search 라고 보기에는 어려울 것 같아요)

**Comment by Dongkyuuuu** [comment]
@ding-co 
작업완료 되어 이슈 종료하도록 하겠습니다!
