### ISSUE TITLE
[FEAT] Slick (slider) 컴포넌트 추가 요청

### ISSUE THREAD

**Issue by ding-co** [depromeet/ggogeet-client#36]
## ✨ 기능 설명

- Slick (slider) 컴포넌트 추가

## ✨ 개발 목록

- [ ] Slick (slider) 컴포넌트

## ✨ 스크린샷

<img width="266" alt="Screenshot 2022-12-01 at 11 42 57 PM" src="https://user-images.githubusercontent.com/80014673/205081721-fe265bf1-19b7-489a-92af-ec945678de0c.png">

<img width="270" alt="Screenshot 2022-12-01 at 11 43 25 PM" src="https://user-images.githubusercontent.com/80014673/205081830-6c04dc45-6117-4fb0-807e-9796f46cdcf2.png">

## ✨ 기타 설명 / 질문

**Comment by Dongkyuuuu** [comment]
혹시 `Slick Carousel`이 정확히 어떤 컴포넌트인가요..?? 슬라이더 같은 개념으로 바라보면 될까요?

**Comment by ding-co** [comment]
> 혹시 `Slick Carousel`이 정확히 어떤 컴포넌트인가요..?? 슬라이더 같은 개념으로 바라보면 될까요?

네네 제가 약간 오해의 소지가 있을 수 있게 말씀을 드렸군요! 슬라이더로 보시면 좋을 것 같습니다.

**Comment by numeru** [comment]
가로 스크롤이 되는 컨테이너 같은데 제가 이해한게 맞을까요?

이거는 안에 들어가는 내용도 다 다르고 세부 스타일도 달라서
사용하시는 곳에서 `overflow-x: auto` 로 처리하시는게 좋지 않을까 싶은데 어떠신가요?

@ding-co

**Comment by ding-co** [comment]
> 가로 스크롤이 되는 컨테이너 같은데 제가 이해한게 맞을까요?
> 
> 이거는 안에 들어가는 내용도 다 다르고 세부 스타일도 달라서 사용하시는 곳에서 `overflow-x: auto` 로 처리하시는게 좋지 않을까 싶은데 어떠신가요?
> 
> 제가 파악하지 못한 다른 공통 기능이 더 있을까요?
> 
> @ding-co

네 그렇게 하면 괜찮을 것 같습니다!

다른 건 아직 잘 모르겠습니다.
