### ISSUE TITLE
[BUG] TopNavigation 공통 컴포넌트 이슈 요청

### ISSUE THREAD

**Issue by ding-co** [depromeet/ggogeet-client#43]
##  🛠 버그 설명 

- [[피그마]
](https://www.figma.com/file/td5T9WbH8dv9xQmnQLVkRR/ggo-geet?node-id=1839%3A34617&t=ECJQEJ0t8mZ4TJYX-0)

TopNavigation 가운데 title 위치 고정 관련 문제

### 🔨 기대한 동작

<img width="343" alt="Screenshot 2022-12-02 at 10 11 00 PM" src="https://user-images.githubusercontent.com/80014673/205302405-eac48919-64ae-4868-9bfa-9ba069d7cc0a.png">

### 🔨 실제 동작 

<img width="380" alt="Screenshot 2022-12-02 at 10 11 06 PM" src="https://user-images.githubusercontent.com/80014673/205302416-6226278f-d26e-479b-8148-45913e128d28.png">

##  🛠 기타 설명 / 질문

피그마와 같이 이쁘게 위치 지정을 시키기 위해 어떻게 하면 좋을까요.

**Comment by Dongkyuuuu** [comment]
@numeru 확인 부탁드려요!
