### ISSUE TITLE
[FEAT] 모바일에서 cursor: pointer CSS 이슈 질문

### ISSUE THREAD

**Issue by ding-co** [depromeet/ggogeet-client#49]
##  🛠 기타 설명 / 질문

[[PR 링크]](https://github.com/depromeet/ggogeet-client/pull/34)

<img width="791" alt="Screenshot 2022-12-04 at 10 35 47 PM" src="https://user-images.githubusercontent.com/80014673/205493697-fda0c038-ca85-4cda-a674-c79b9aaa5662.png">

동규님 PR merge 되면서 close 되어 이슈로 질문 남깁니다.
모바일에서 CSS cursor: pointer;로 주면 불필요한 outline 같은 것이 생긴다고 하셨는데,
정확히 어떤 부분에서 문제가 발생되어 말씀하신 걸까요.

저도 이와 관련되어 궁금증이 생겨 현직 퍼블리셔한테 질문을 남겨 답변을 받은 것을 공유드립니다~

---
<img width="591" alt="Screenshot 2022-12-04 at 10 39 56 PM" src="https://user-images.githubusercontent.com/80014673/205493868-65f609f0-3d9c-4454-9eae-080bc810ae0b.png">

<아이폰 사파리 테스트>

https://user-images.githubusercontent.com/80014673/205493830-473ae64a-ae3c-4f26-b283-70231b722e11.mp4

<아이폰 크롬 테스트>

https://user-images.githubusercontent.com/80014673/205493834-51e9575b-9357-4358-a359-830a9b051368.mp4

[[W3 스펙 명세서 링크]](https://w3c.github.io/csswg-drafts/css-ui/#cursor)

**Comment by Dongkyuuuu** [comment]
정확한 프로퍼티 이름은 몰랐는데 `tap-highlight`가 맞는 것 같네요! 
`cursor: pointer`에 `tap-highlight`가 추가 되는 것 같네요.

desktop까지 대응하게 된다면 어쩔 수 없겠지만, 모바일 상에서만 사용 되고, 해당 터치 인터렉션에 관해서 추가 적인 논의가 필요해서 우선 빼고 진행 했었습니다!
터치에 대한 느낌도 개인적으로는 터치 이후 진행되는 추가적인 액션에 의해 터치를 했다고 사용자가 느낄 수 있다고 판단하긴 했습니다.
리뷰 다시 살펴보니 버튼 컴포넌트 이네요. 저는 버튼은 아니고 리스트이긴 했는데 필요하시다면 디자인요청 드려서 진행해봐도 될 것 같습니다

저의 케이스는 아래 첨부한 영상과 같은 케이스 였습니다.

### 포인터 미적용
https://user-images.githubusercontent.com/16554536/205502852-9a6e45ed-fa7f-4fac-b631-d1a3d402eed8.mov

### 포인터 적용
https://user-images.githubusercontent.com/16554536/205502873-b6a0f9aa-971d-4ff2-9943-8cb58f0c16a7.mov

**Comment by ding-co** [comment]
> 정확한 프로퍼티 이름은 몰랐는데 `tap-highlight`가 맞는 것 같네요! 
> 
> `cursor: pointer`에 `tap-highlight`가 추가 되는 것 같네요.
> 
> 
> 
> desktop까지 대응하게 된다면 어쩔 수 없겠지만, 모바일 상에서만 사용 되고, 해당 터치 인터렉션에 관해서 추가 적인 논의가 필요해서 우선 빼고 진행 했었습니다!
> 
> 터치에 대한 느낌도 개인적으로는 터치 이후 진행되는 추가적인 액션에 의해 터치를 했다고 사용자가 느낄 수 있다고 판단하긴 했습니다.
> 
> 리뷰 다시 살펴보니 버튼 컴포넌트 이네요. 저는 버튼은 아니고 리스트이긴 했는데 필요하시다면 디자인요청 드려서 진행해봐도 될 것 같습니다
> 
> 
> 
> 저의 케이스는 아래 첨부한 영상과 같은 케이스 였습니다.
> 
> 
> 
> ### 포인터 미적용
> 
> https://user-images.githubusercontent.com/16554536/205502852-9a6e45ed-fa7f-4fac-b631-d1a3d402eed8.mov
> 
> 
> 
> ### 포인터 적용
> 
> https://user-images.githubusercontent.com/16554536/205502873-b6a0f9aa-971d-4ff2-9943-8cb58f0c16a7.mov
> 
> 

아하 요런 이슈였군요!
답변 감사합니다.
