### ISSUE TITLE
[FEAT] 탭 컴포넌트 개발 요청

### ISSUE THREAD

**Issue by ding-co** [depromeet/ggogeet-client#58]
## ✨ 기능 설명

- 탭 기본 컴포넌트가 필요할 것 같습니다.
- 탭이 구성되는 디자인은 다 달라서 외부에서 ReactNode 형태로 element를 전달하면 해당 element 들로 탭 UI를 구성하고
  내부에서 각 탭을 클릭했을 때 렌더링 되는 로직만 컴포넌트로 만들면 좋지 않을까 싶습니다.
- 렌더링 성능 차원에서 한 번에 탭들에 대한 모든 데이터를 받기 보다는
  각 탭 아이템들에 대한 데이터 API를 호출하는 형식으로 하면 좋을 것 같습니다.
  -> 탭 컨테이너 (보여지는 기본 탭),
       탭 아이템 컴포넌트는 탭 컨테이너에 종속되는 방식으로 각 아이템에 props로 외부에서 API를 호출하여 받은 데이터를 inject하여
       하단에 내용들을 렌더링 하는 로직은 어떨까 싶습니다.)

## ✨ 개발 목록

- [ ] 탭 기본 컴포넌트

## ✨ 스크린샷

- 가이드라인에서 탭별 (상황별) 선택

<img width="396" alt="Screenshot 2022-12-06 at 11 37 12 PM" src="https://user-images.githubusercontent.com/80014673/205940873-69cf3f4f-e1e7-4625-b077-3f9a908dbe46.png">

- 리마인드 탭

<img width="232" alt="Screenshot 2022-12-06 at 11 39 15 PM" src="https://user-images.githubusercontent.com/80014673/205941392-c561b800-9674-4861-b5f8-6ad6ca60b4d3.png">

- 편지 보관함 탭

<img width="242" alt="Screenshot 2022-12-06 at 11 40 31 PM" src="https://user-images.githubusercontent.com/80014673/205942235-b24354f9-7a76-4ea2-9547-f6295fc712f5.png">

- 받은 편지 추가 탭

<img width="266" alt="Screenshot 2022-12-06 at 11 42 54 PM" src="https://user-images.githubusercontent.com/80014673/205942388-499643bd-c410-4224-8dc9-3ca75ca7bc46.png">

등...

**Comment by ding-co** [comment]
공통적인 컴포넌트로 개발이 조금 어렵다고 생각 되시면 각 페이지에서 각자 원하는 방식으로 구현하는 쪽으로 방향을 잡아도 됩니다..!

**Comment by numeru** [comment]
상단에 메뉴를 클릭했을 때 하단에 내용이 바뀌는 형태인거죠?

말씀하신 것처럼 사용하는 곳마다 스타일과 기능 차이가 크고
상단 메뉴도 ReactNode 로 받고 하단 내용도 children 으로 받으면 공통 컴포넌트로서 큰 의미가 없는 것 같아서
조금 애매한 것 같다는 생각이 드네요

이건 일단 각 페이지에서 구현하는걸로 해도 괜찮으실까요?

**Comment by ding-co** [comment]
> 상단에 메뉴를 클릭했을 때 하단에 내용이 바뀌는 형태인거죠?
> 
> 말씀하신 것처럼 사용하는 곳마다 스타일과 기능 차이가 크고 상단 메뉴도 ReactNode 로 받고 하단 내용도 children 으로 받으면 공통 컴포넌트로서 큰 의미가 없는 것 같아서 조금 애매한 것 같다는 생각이 드네요
> 
> 이건 일단 각 페이지에서 구현하는걸로 해도 괜찮으실까요?

네 괜찮습니다!
