### ISSUE TITLE
[FEAT] Carousel 컴포넌트 요청

### ISSUE THREAD

**Issue by ding-co** [depromeet/ggogeet-client#74]
## ✨ 기능 설명

- 좌우 스와이프 가능하고 아래 dot 표시가 있는 Carousel 컴포넌트

## ✨ 개발 목록

- [ ] Carousel 컴포넌트

## ✨ 스크린샷

<img width="269" alt="Screenshot 2022-12-25 at 3 28 21 PM" src="https://user-images.githubusercontent.com/80014673/209458951-741640e4-aeed-4a24-88b6-63028af8c9b1.png">

## ✨ 기타 설명 / 질문

라이브러리 활용하면 좋을 것 같습니다.

**Comment by Dongkyuuuu** [comment]
이건 [react-slick](https://react-slick.neostack.com/) 요 라이브러리로 대체 하겠습니다~
