### ISSUE TITLE
[BUG] 홈, 편지 작성 이슈 공유

### ISSUE THREAD

**Issue by ding-co** [depromeet/ggogeet-client#97]
##  🛠 버그 설명 

- 편지 작성 UI
  - autoFocus - next.js 이용하여 dynamic import를 해서 그런지 원하는 대로 control이 되지 않음 (임시로 해둠)
  - 바텀 시트 열렸을 때 바깥 다른 모든 버튼 event prevent
  - 가이드라인 - 가이드 문구 클릭 시 텍스트 에디터에 추가 되는데 기존 스타일 적용까지 하려면 추가적인 리소스 필요...
    (공식 문서에서 제공해주는 것이 적어서 오픈소스 내부 다 보면서 해야 하는데 쉽지 않음)
  - 완료 화면1 에서 쌍따옴표와 입력하는 글자 사이 간격이 글자 수가 늘어날수록 벌어짐
  - 완료 화면1 에서 한글로 꽉 차게 20자까지 입력하고 완료 화면2 를 보면 input text width가 조금 잘림
     => 임시로 우선 ...으로 처리함
  
##  🛠 기타 설명 / 질문

- 홈 (이미지 교체, 디자인 수정) ✅
- 메모 - 스크롤 관련 height 체크 ✅
- 크롬/사파리/카카오 인앱 등으로 QA 체크 필요 ✅
- input/textarea autoFocus 등 체크 ✅
- 모바일 이미지 해상도 깨짐 ✅

**Comment by ding-co** [comment]
@KimGaeun0806 @Dongkyuuuu @numeru 

UI 작업하면서 눈에 보이거나 생각나는 것들은 최대한 이슈를 처리했습니다.
위에는 해결하려고 시도했거나 아직 시간 관계상 하지 못한 이슈들입니다.
한번씩 체크해주세요.

**Comment by Dongkyuuuu** [comment]
350자는 값이 350자 넘어가면 저장안하게끔 처리하는 방법은 어떤가요

**Comment by ding-co** [comment]
> 350자는 값이 350자 넘어가면 저장안하게끔 처리하는 방법은 어떤가요

텍스트 에디터에는 계속 입력 되지만 저장 버튼 누르면 정규식 이용해서 처리할 수는 있습니다.

**Comment by ding-co** [comment]
우선 텍스트 제한은 MVP에서 뺐습니다.
